services:
  kiosk:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    depends_on:
      - db
    env_file:
      - path: ../.env
        required: true # default
    links:
      - "db:database"
    ports:
      - "3000:3000"
    volumes:
      - ../..:/workspaces:cached
      - type: bind
        source: ./zsh
        target: /home/vscode/zshfiles

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    networks:
      - kiosk

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - path: ../.env
        required: true # default
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - kiosk


networks:
  kiosk:

volumes:
  postgres-data: